name: Infrastructure
on: pull_request
jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [alpha, beta, main]
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 0.13.0
      - working-directory: infrastructure/environments/${{ matrix.environment }}
        run: |
          terraform fmt
      - working-directory: infrastructure/environments/${{ matrix.environment }}
        run: |
          terraform init
      - working-directory: infrastructure/environments/${{ matrix.environment }}
        run: |
          terraform validate
