name: Release
on:
  push:
    branches:
      - alpha
      - beta
      - main
jobs:
  release:
    if: github.actor != 'sentrei-bot'
    runs-on: ubuntu-latest
    needs: context
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v2.1.1
        with:
          always-auth: false
          node-version: "14.4.0"
          registry-url: https://registry.npmjs.org
          scope: "@sentrei"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/cache@v2.1.1
        with:
          path: |
            **/node_modules
          key: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run typescript
      - run: |
          yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: "sentrei-bot"
          GIT_COMMITTER_NAME: "sentrei-bot"
          GIT_AUTHOR_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
          GIT_COMMITTER_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
      - if: needs.context.outputs.branch != 'main'
        run: |
          echo "::set-env name=DIST_TAG::${GITHUB_REF#refs/heads/}"
      - if: needs.context.outputs.branch == 'main'
        run: |
          echo "::set-env name=DIST_TAG::latest"
      - run: |
          cat <<< $(jq '.private = false' package.json) > package.json && npm publish . --tag $DIST_TAG || true
          cat <<< $(jq '.private = true' package.json) > package.json
          git reset --hard --recurse-submodule && yarn run publish:lerna || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - id: release
        run: |
          version=$(node -pe "require('./package.json').version")
          echo "::set-output name=release::${version}"
      - run: |
          yarn run sentry:release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ github.repository_owner }}
          SENTRY_ENVIRONMENT: ${GITHUB_REF#refs/heads/}
          SENTRY_RELEASE: ${{ steps.release.outputs.release }}
